# Jupyter Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ''
author: Curvenote
logo: images/logo.svg

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://curvenote.com/@docs/cli

html:
  favicon: images/favicon.ico
  google_analytics_id: G-4P4Z3X7QKB
  extra_navbar: Written in <a href="https://curvenote.com">Curvenote</a>
